// AUTO-GENERATED by scripts/build-spotcheck-fixtures.py
// Source: C:/spotcheck/spotcheck/test-data/flights/*.json
// GPS coordinates have been jittered to a fixed dummy region.
// Edit the script, not this file.

import type { Sample } from "./types";

export const samples: Sample[] = [
  {
    id: "clean-site",
    name: "Clean inspection · 293 photos",
    description: "A standard tower site flown end-to-end: downlook orbit, uplook orbit, center-in/out passes, a cable run, and a small ambiguous bucket the metadata-first pass flags for review before upload.",
    photoCount: 293,
    timeRange: {
      start: "2025-09-19T05:15:43",
      end: "2025-09-19T05:27:51"
    },
    altitudeRange: {
      min: 6.1,
      max: 53.6
    },
    pitchRange: {
      min: -34.9,
      max: 20.0
    },
    requiredCategories: [
      "downlook",
      "uplook",
      "center in",
      "center out",
      "cable run",
      "top down"
    ],
    segments: [
      {
        id: "downlook",
        category: "Downlook orbit",
        rawCategory: "downlook",
        photoCount: 62,
        orbitType: "full",
        totalRotation: 363.5,
        medianPitch: -34.9,
        medianAltitude: 52.6,
        imageWidth: 5280,
        rule: "pitch -35° within ±3° of −35°, rotation 364° ≥ 350° → Downlook orbit",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0050.JPG",
            createDate: "2025-09-19 05:18:36",
            lat: 38.907195,
            lon: -77.036963,
            altitude: 52.8,
            gimbalPitch: -34.9,
            gimbalYaw: 99.7,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0065.JPG",
            createDate: "2025-09-19 05:19:06",
            lat: 38.907247,
            lon: -77.036912,
            altitude: 52.6,
            gimbalPitch: -34.9,
            gimbalYaw: -175.2,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0080.JPG",
            createDate: "2025-09-19 05:19:36",
            lat: 38.907201,
            lon: -77.03684,
            altitude: 52.5,
            gimbalPitch: -34.9,
            gimbalYaw: -73.8,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0095.JPG",
            createDate: "2025-09-19 05:20:06",
            lat: 38.907159,
            lon: -77.036885,
            altitude: 52.5,
            gimbalPitch: -34.9,
            gimbalYaw: 2.3,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "uplook",
        category: "Uplook orbit",
        rawCategory: "uplook",
        photoCount: 60,
        orbitType: "full",
        totalRotation: 359.3,
        medianPitch: 20.0,
        medianAltitude: 47.0,
        imageWidth: 5280,
        rule: "pitch 20° within ±3° of +20°, rotation 359° ≥ 70° → Uplook orbit",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0173.JPG",
            createDate: "2025-09-19 05:23:04",
            lat: 38.9072,
            lon: -77.036959,
            altitude: 47.0,
            gimbalPitch: 20.0,
            gimbalYaw: 101.7,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0188.JPG",
            createDate: "2025-09-19 05:23:34",
            lat: 38.907252,
            lon: -77.036902,
            altitude: 46.9,
            gimbalPitch: 20.0,
            gimbalYaw: -166.9,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0203.JPG",
            createDate: "2025-09-19 05:24:04",
            lat: 38.907207,
            lon: -77.036829,
            altitude: 47.1,
            gimbalPitch: 20.0,
            gimbalYaw: -82.5,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0218.JPG",
            createDate: "2025-09-19 05:24:34",
            lat: 38.907154,
            lon: -77.036902,
            altitude: 47.1,
            gimbalPitch: 20.0,
            gimbalYaw: 19.8,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "center-in",
        category: "Center in",
        rawCategory: "center in",
        photoCount: 61,
        orbitType: "full",
        totalRotation: 363.9,
        medianPitch: 0.0,
        medianAltitude: 48.7,
        imageWidth: 5280,
        rule: "pitch 0° within ±3° of 0°, heading toward tower → Center in",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0112.JPG",
            createDate: "2025-09-19 05:20:49",
            lat: 38.907203,
            lon: -77.036964,
            altitude: 48.7,
            gimbalPitch: 0.0,
            gimbalYaw: 103.3,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0127.JPG",
            createDate: "2025-09-19 05:21:19",
            lat: 38.907241,
            lon: -77.036865,
            altitude: 48.8,
            gimbalPitch: 0.0,
            gimbalYaw: -129.4,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0142.JPG",
            createDate: "2025-09-19 05:21:49",
            lat: 38.907191,
            lon: -77.036842,
            altitude: 48.7,
            gimbalPitch: 0.0,
            gimbalYaw: -54.3,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0157.JPG",
            createDate: "2025-09-19 05:22:19",
            lat: 38.907159,
            lon: -77.036896,
            altitude: 48.7,
            gimbalPitch: 0.0,
            gimbalYaw: 15.3,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "center-out",
        category: "Center out",
        rawCategory: "center out",
        photoCount: 61,
        orbitType: "full",
        totalRotation: 365.0,
        medianPitch: 0.0,
        medianAltitude: 49.1,
        imageWidth: 5280,
        rule: "pitch 0° within ±3° of 0°, heading away from tower → Center out",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0233.JPG",
            createDate: "2025-09-19 05:25:51",
            lat: 38.907227,
            lon: -77.036962,
            altitude: 48.9,
            gimbalPitch: 0.0,
            gimbalYaw: -54.0,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0248.JPG",
            createDate: "2025-09-19 05:26:21",
            lat: 38.907155,
            lon: -77.036893,
            altitude: 49.1,
            gimbalPitch: 0.0,
            gimbalYaw: -153.6,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0263.JPG",
            createDate: "2025-09-19 05:26:51",
            lat: 38.907188,
            lon: -77.036834,
            altitude: 49.0,
            gimbalPitch: 0.0,
            gimbalYaw: 108.6,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0278.JPG",
            createDate: "2025-09-19 05:27:21",
            lat: 38.907237,
            lon: -77.036906,
            altitude: 49.1,
            gimbalPitch: 0.0,
            gimbalYaw: 18.3,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "unknown-flight-category-check-gimbal-angle",
        category: "Needs review (gimbal angle)",
        rawCategory: "unknown flight category check gimbal angle",
        photoCount: 31,
        orbitType: "N/A",
        totalRotation: null,
        medianPitch: -30.0,
        medianAltitude: 6.2,
        imageWidth: 5280,
        rule: "pitch -30° outside known category windows → Needs review",
        qaStatus: "NEEDS_REVIEW",
        samplePhotos: [
          {
            fileName: "DJI_0001.JPG",
            createDate: "2025-09-19 05:15:43",
            lat: 38.907246,
            lon: -77.03688,
            altitude: 6.1,
            gimbalPitch: -30.0,
            gimbalYaw: -172.7,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0008.JPG",
            createDate: "2025-09-19 05:15:57",
            lat: 38.907215,
            lon: -77.036805,
            altitude: 6.1,
            gimbalPitch: -30.0,
            gimbalYaw: -102.9,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0015.JPG",
            createDate: "2025-09-19 05:16:11",
            lat: 38.907156,
            lon: -77.036815,
            altitude: 6.2,
            gimbalPitch: -30.0,
            gimbalYaw: -33.9,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0022.JPG",
            createDate: "2025-09-19 05:16:25",
            lat: 38.907144,
            lon: -77.036894,
            altitude: 6.2,
            gimbalPitch: -30.0,
            gimbalYaw: 42.3,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "cable-run",
        category: "Cable run",
        rawCategory: "cable run",
        photoCount: 18,
        orbitType: "N/A",
        totalRotation: null,
        medianPitch: -24.9,
        medianAltitude: 37.75,
        imageWidth: 5280,
        rule: "pitch -25° within ±3° of −22°, altitude 38m > 20m → Cable run",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0032.JPG",
            createDate: "2025-09-19 05:17:17",
            lat: 38.907197,
            lon: -77.036971,
            altitude: 21.2,
            gimbalPitch: -24.9,
            gimbalYaw: 101.3,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0036.JPG",
            createDate: "2025-09-19 05:17:25",
            lat: 38.907196,
            lon: -77.036971,
            altitude: 29.1,
            gimbalPitch: -24.9,
            gimbalYaw: 101.0,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0040.JPG",
            createDate: "2025-09-19 05:17:33",
            lat: 38.907196,
            lon: -77.036971,
            altitude: 37.0,
            gimbalPitch: -24.9,
            gimbalYaw: 101.0,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0044.JPG",
            createDate: "2025-09-19 05:17:41",
            lat: 38.907196,
            lon: -77.03697,
            altitude: 44.2,
            gimbalPitch: -24.9,
            gimbalYaw: 101.0,
            imageWidth: 5280
          }
        ]
      }
    ]
  },
  {
    id: "tower-site",
    name: "Tower-heavy job · 379 photos",
    description: "A tower-heavy capture set with three orbit passes, two descents, and compound upper/lower passes. Useful for showing how FlightSorter decomposes a busier flight log into structured segments.",
    photoCount: 379,
    timeRange: {
      start: "2025-09-19T04:59:58",
      end: "2025-09-19T05:15:41"
    },
    altitudeRange: {
      min: 6.0,
      max: 53.0
    },
    pitchRange: {
      min: -90.0,
      max: 0.0
    },
    requiredCategories: [
      "tower flight type 2",
      "compound flight upper",
      "compound flight lower",
      "Orbit 1",
      "Orbit 2",
      "Orbit 3"
    ],
    segments: [
      {
        id: "center-incorrect",
        category: "Center — incorrect",
        rawCategory: "center incorrect",
        photoCount: 0,
        orbitType: "full",
        totalRotation: 0.0,
        medianPitch: 0.0,
        medianAltitude: 0.0,
        imageWidth: 4000,
        rule: "pitch 0° within ±3° of 0°, heading toward tower → Center in",
        qaStatus: "PASSED",
        samplePhotos: []
      },
      {
        id: "top-down",
        category: "Top down",
        rawCategory: "top down",
        photoCount: 1,
        orbitType: "full",
        totalRotation: 0.0,
        medianPitch: -90.0,
        medianAltitude: 52.6,
        imageWidth: 5280,
        rule: "pitch -90° within ±3° of −90° → Top down",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0622.JPG",
            createDate: "2025-09-19 05:00:27",
            lat: 38.907204,
            lon: -77.036898,
            altitude: 52.6,
            gimbalPitch: -90.0,
            gimbalYaw: 15.1,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "tower-flight-type-2",
        category: "Tower flight (type 2)",
        rawCategory: "tower Flight type 2",
        photoCount: 295,
        orbitType: "N/A",
        totalRotation: null,
        medianPitch: -50.2,
        medianAltitude: 40.2,
        imageWidth: 5280,
        rule: "pitch -50° within ±3° of −50° → Tower flight (type 2)",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0623.JPG",
            createDate: "2025-09-19 05:01:42",
            lat: 38.907132,
            lon: -77.036884,
            altitude: 52.7,
            gimbalPitch: -50.2,
            gimbalYaw: 11.3,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0696.JPG",
            createDate: "2025-09-19 05:04:08",
            lat: 38.907223,
            lon: -77.036817,
            altitude: 52.8,
            gimbalPitch: -50.2,
            gimbalYaw: -86.3,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0769.JPG",
            createDate: "2025-09-19 05:06:35",
            lat: 38.907252,
            lon: -77.036937,
            altitude: 39.6,
            gimbalPitch: -50.2,
            gimbalYaw: 160.5,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0842.JPG",
            createDate: "2025-09-19 05:09:01",
            lat: 38.907165,
            lon: -77.036954,
            altitude: 22.9,
            gimbalPitch: -50.2,
            gimbalYaw: 68.3,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "compound-flight-upper",
        category: "Compound — upper",
        rawCategory: "compound flight upper",
        photoCount: 67,
        orbitType: "N/A",
        totalRotation: null,
        medianPitch: -44.6,
        medianAltitude: 17.5,
        imageWidth: 5280,
        rule: "pitch -45° within ±3° of −45° → Compound (upper)",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0918.JPG",
            createDate: "2025-09-19 05:12:21",
            lat: 38.907273,
            lon: -77.03707,
            altitude: 17.4,
            gimbalPitch: -44.6,
            gimbalYaw: 134.4,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0934.JPG",
            createDate: "2025-09-19 05:12:52",
            lat: 38.907344,
            lon: -77.036857,
            altitude: 17.5,
            gimbalPitch: -44.6,
            gimbalYaw: -137.1,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0950.JPG",
            createDate: "2025-09-19 05:13:24",
            lat: 38.907187,
            lon: -77.036714,
            altitude: 17.6,
            gimbalPitch: -44.6,
            gimbalYaw: -42.9,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0966.JPG",
            createDate: "2025-09-19 05:13:56",
            lat: 38.907074,
            lon: -77.036958,
            altitude: 17.5,
            gimbalPitch: -44.6,
            gimbalYaw: 45.1,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "compound-flight-lower",
        category: "Compound — lower",
        rawCategory: "compound flight lower",
        photoCount: 15,
        orbitType: "N/A",
        totalRotation: null,
        medianPitch: -30.0,
        medianAltitude: 6.1,
        imageWidth: 5280,
        rule: "pitch -30° in range [−30°, −15°] → Compound (lower)",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0985.JPG",
            createDate: "2025-09-19 05:15:13",
            lat: 38.907144,
            lon: -77.036891,
            altitude: 6.0,
            gimbalPitch: -30.0,
            gimbalYaw: 44.7,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0988.JPG",
            createDate: "2025-09-19 05:15:19",
            lat: 38.907153,
            lon: -77.036908,
            altitude: 6.1,
            gimbalPitch: -30.0,
            gimbalYaw: 54.1,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0991.JPG",
            createDate: "2025-09-19 05:15:25",
            lat: 38.907181,
            lon: -77.036935,
            altitude: 6.1,
            gimbalPitch: -30.0,
            gimbalYaw: 88.6,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0994.JPG",
            createDate: "2025-09-19 05:15:31",
            lat: 38.907209,
            lon: -77.036945,
            altitude: 6.1,
            gimbalPitch: -30.0,
            gimbalYaw: 124.0,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "orbit-1",
        category: "Orbit pass 1",
        rawCategory: "Orbit 1",
        photoCount: 104,
        orbitType: "N/A",
        totalRotation: 361.6,
        medianPitch: -50.2,
        medianAltitude: 52.8,
        imageWidth: 5280,
        rule: "orbit-like rotation 362°, pitch -50° → Orbit 1",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0623.JPG",
            createDate: "2025-09-19 05:01:42",
            lat: 38.907132,
            lon: -77.036884,
            altitude: 52.7,
            gimbalPitch: -50.2,
            gimbalYaw: 11.3,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0649.JPG",
            createDate: "2025-09-19 05:02:34",
            lat: 38.907169,
            lon: -77.036957,
            altitude: 52.7,
            gimbalPitch: -50.2,
            gimbalYaw: 73.0,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0675.JPG",
            createDate: "2025-09-19 05:03:26",
            lat: 38.907267,
            lon: -77.036914,
            altitude: 52.7,
            gimbalPitch: -50.2,
            gimbalYaw: -176.3,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0701.JPG",
            createDate: "2025-09-19 05:04:18",
            lat: 38.907207,
            lon: -77.036814,
            altitude: 52.9,
            gimbalPitch: -50.2,
            gimbalYaw: -72.5,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "descent-1",
        category: "Descent 1",
        rawCategory: "Descent 1",
        photoCount: 7,
        orbitType: "N/A",
        totalRotation: null,
        medianPitch: -50.2,
        medianAltitude: 47.4,
        imageWidth: 5280,
        rule: "descending altitude profile → Descent 1",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0727.JPG",
            createDate: "2025-09-19 05:05:11",
            lat: 38.907144,
            lon: -77.036886,
            altitude: 52.4,
            gimbalPitch: -50.2,
            gimbalYaw: 12.6,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0728.JPG",
            createDate: "2025-09-19 05:05:13",
            lat: 38.907145,
            lon: -77.036887,
            altitude: 51.1,
            gimbalPitch: -50.2,
            gimbalYaw: 12.6,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0729.JPG",
            createDate: "2025-09-19 05:05:15",
            lat: 38.907145,
            lon: -77.036887,
            altitude: 49.2,
            gimbalPitch: -50.2,
            gimbalYaw: 12.6,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0730.JPG",
            createDate: "2025-09-19 05:05:17",
            lat: 38.907145,
            lon: -77.036887,
            altitude: 47.4,
            gimbalPitch: -50.2,
            gimbalYaw: 12.7,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "orbit-2",
        category: "Orbit pass 2",
        rawCategory: "Orbit 2",
        photoCount: 91,
        orbitType: "N/A",
        totalRotation: 377.7,
        medianPitch: -50.2,
        medianAltitude: 39.9,
        imageWidth: 5280,
        rule: "orbit-like rotation 378°, pitch -50° → Orbit 2",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0734.JPG",
            createDate: "2025-09-19 05:05:25",
            lat: 38.907144,
            lon: -77.036886,
            altitude: 39.8,
            gimbalPitch: -50.2,
            gimbalYaw: 12.6,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0756.JPG",
            createDate: "2025-09-19 05:06:09",
            lat: 38.9072,
            lon: -77.036967,
            altitude: 39.3,
            gimbalPitch: -50.2,
            gimbalYaw: 99.6,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0778.JPG",
            createDate: "2025-09-19 05:06:53",
            lat: 38.907272,
            lon: -77.036897,
            altitude: 39.8,
            gimbalPitch: -50.2,
            gimbalYaw: -163.3,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0800.JPG",
            createDate: "2025-09-19 05:07:37",
            lat: 38.907196,
            lon: -77.036812,
            altitude: 40.4,
            gimbalPitch: -50.2,
            gimbalYaw: -61.7,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "descent-2",
        category: "Descent 2",
        rawCategory: "Descent 2",
        photoCount: 8,
        orbitType: "N/A",
        totalRotation: null,
        medianPitch: -50.2,
        medianAltitude: 33.4,
        imageWidth: 5280,
        rule: "descending altitude profile → Descent 2",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0825.JPG",
            createDate: "2025-09-19 05:08:27",
            lat: 38.907148,
            lon: -77.036915,
            altitude: 40.2,
            gimbalPitch: -50.2,
            gimbalYaw: 31.1,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0827.JPG",
            createDate: "2025-09-19 05:08:31",
            lat: 38.907148,
            lon: -77.036914,
            altitude: 36.4,
            gimbalPitch: -50.2,
            gimbalYaw: 31.1,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0829.JPG",
            createDate: "2025-09-19 05:08:35",
            lat: 38.907148,
            lon: -77.036914,
            altitude: 32.4,
            gimbalPitch: -50.2,
            gimbalYaw: 31.1,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0831.JPG",
            createDate: "2025-09-19 05:08:39",
            lat: 38.907147,
            lon: -77.036914,
            altitude: 28.5,
            gimbalPitch: -50.2,
            gimbalYaw: 31.1,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "orbit-3",
        category: "Orbit pass 3",
        rawCategory: "Orbit 3",
        photoCount: 85,
        orbitType: "N/A",
        totalRotation: 370.7,
        medianPitch: -50.2,
        medianAltitude: 23.6,
        imageWidth: 5280,
        rule: "orbit-like rotation 371°, pitch -50° → Orbit 3",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0833.JPG",
            createDate: "2025-09-19 05:08:43",
            lat: 38.907147,
            lon: -77.036914,
            altitude: 24.6,
            gimbalPitch: -50.2,
            gimbalYaw: 31.1,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0854.JPG",
            createDate: "2025-09-19 05:09:25",
            lat: 38.907227,
            lon: -77.036969,
            altitude: 23.3,
            gimbalPitch: -50.2,
            gimbalYaw: 135.7,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0875.JPG",
            createDate: "2025-09-19 05:10:07",
            lat: 38.907255,
            lon: -77.036845,
            altitude: 23.6,
            gimbalPitch: -50.2,
            gimbalYaw: -123.8,
            imageWidth: 5280
          },
          {
            fileName: "DJI_0896.JPG",
            createDate: "2025-09-19 05:10:49",
            lat: 38.907178,
            lon: -77.036832,
            altitude: 23.7,
            gimbalPitch: -50.2,
            gimbalYaw: -41.6,
            imageWidth: 5280
          }
        ]
      }
    ]
  },
  {
    id: "smoke",
    name: "Smoke test · 2 photos",
    description: "The smallest possible drop: one top-down photo and one cable-anchor photo. Shows the pure metadata-only path with no orbit logic.",
    photoCount: 2,
    timeRange: {
      start: "2024-04-24T12:03:57",
      end: "2024-04-24T12:04:23"
    },
    altitudeRange: {
      min: 113.5,
      max: 114.5
    },
    pitchRange: {
      min: -90.0,
      max: -27.5
    },
    requiredCategories: [
      "top down",
      "cable anchor"
    ],
    segments: [
      {
        id: "top-down",
        category: "Top down",
        rawCategory: "top down",
        photoCount: 1,
        orbitType: "full",
        totalRotation: 0.0,
        medianPitch: -90.0,
        medianAltitude: 114.5,
        imageWidth: 5280,
        rule: "pitch -90° within ±3° of −90° → Top down",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0954.JPG",
            createDate: "2024-04-24 12:04:23",
            lat: 38.907237,
            lon: -77.036906,
            altitude: 114.5,
            gimbalPitch: -90.0,
            gimbalYaw: -3.3,
            imageWidth: 5280
          }
        ]
      },
      {
        id: "cable-anchor",
        category: "Cable anchor",
        rawCategory: "cable anchor",
        photoCount: 1,
        orbitType: "full",
        totalRotation: 0.0,
        medianPitch: -27.5,
        medianAltitude: 113.5,
        imageWidth: 4000,
        rule: "image width 4000px < 5280px → Cable anchor (zoomed)",
        qaStatus: "PASSED",
        samplePhotos: [
          {
            fileName: "DJI_0953.JPG",
            createDate: "2024-04-24 12:03:57",
            lat: 38.907163,
            lon: -77.036894,
            altitude: 113.5,
            gimbalPitch: -27.5,
            gimbalYaw: -4.1,
            imageWidth: 4000
          }
        ]
      }
    ]
  }
];

export const correction: Sample = {
  id: "clean-site-v2",
  name: "Clean inspection · 293 photos",
  description: "A standard tower site flown end-to-end: downlook orbit, uplook orbit, center-in/out passes, a cable run, and a small ambiguous bucket the metadata-first pass flags for review before upload.",
  photoCount: 293,
  timeRange: {
    start: "2025-09-19T05:15:43",
    end: "2025-09-19T05:27:51"
  },
  altitudeRange: {
    min: 6.1,
    max: 53.6
  },
  pitchRange: {
    min: -34.9,
    max: 20.0
  },
  requiredCategories: [
    "downlook",
    "uplook",
    "center in",
    "center out",
    "cable run",
    "top down"
  ],
  segments: [
    {
      id: "downlook",
      category: "Downlook orbit",
      rawCategory: "downlook",
      photoCount: 62,
      orbitType: "full",
      totalRotation: 363.5,
      medianPitch: -34.9,
      medianAltitude: 52.6,
      imageWidth: 5280,
      rule: "pitch -35° within ±3° of −35°, rotation 364° ≥ 350° → Downlook orbit",
      qaStatus: "PASSED",
      samplePhotos: [
        {
          fileName: "DJI_0050.JPG",
          createDate: "2025-09-19 05:18:36",
          lat: 38.907195,
          lon: -77.036963,
          altitude: 52.8,
          gimbalPitch: -34.9,
          gimbalYaw: 99.7,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0065.JPG",
          createDate: "2025-09-19 05:19:06",
          lat: 38.907247,
          lon: -77.036912,
          altitude: 52.6,
          gimbalPitch: -34.9,
          gimbalYaw: -175.2,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0080.JPG",
          createDate: "2025-09-19 05:19:36",
          lat: 38.907201,
          lon: -77.03684,
          altitude: 52.5,
          gimbalPitch: -34.9,
          gimbalYaw: -73.8,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0095.JPG",
          createDate: "2025-09-19 05:20:06",
          lat: 38.907159,
          lon: -77.036885,
          altitude: 52.5,
          gimbalPitch: -34.9,
          gimbalYaw: 2.3,
          imageWidth: 5280
        }
      ],
      version: 1
    },
    {
      id: "uplook",
      category: "Uplook orbit",
      rawCategory: "uplook",
      photoCount: 60,
      orbitType: "full",
      totalRotation: 359.3,
      medianPitch: 20.0,
      medianAltitude: 47.0,
      imageWidth: 5280,
      rule: "pitch 20° within ±3° of +20°, rotation 359° ≥ 70° → Uplook orbit",
      qaStatus: "PASSED",
      samplePhotos: [
        {
          fileName: "DJI_0173.JPG",
          createDate: "2025-09-19 05:23:04",
          lat: 38.9072,
          lon: -77.036959,
          altitude: 47.0,
          gimbalPitch: 20.0,
          gimbalYaw: 101.7,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0188.JPG",
          createDate: "2025-09-19 05:23:34",
          lat: 38.907252,
          lon: -77.036902,
          altitude: 46.9,
          gimbalPitch: 20.0,
          gimbalYaw: -166.9,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0203.JPG",
          createDate: "2025-09-19 05:24:04",
          lat: 38.907207,
          lon: -77.036829,
          altitude: 47.1,
          gimbalPitch: 20.0,
          gimbalYaw: -82.5,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0218.JPG",
          createDate: "2025-09-19 05:24:34",
          lat: 38.907154,
          lon: -77.036902,
          altitude: 47.1,
          gimbalPitch: 20.0,
          gimbalYaw: 19.8,
          imageWidth: 5280
        }
      ],
      version: 1
    },
    {
      id: "center-in",
      category: "Center in",
      rawCategory: "center in",
      photoCount: 61,
      orbitType: "full",
      totalRotation: 363.9,
      medianPitch: 0.0,
      medianAltitude: 48.7,
      imageWidth: 5280,
      rule: "pitch 0° within ±3° of 0°, heading toward tower → Center in",
      qaStatus: "PASSED",
      samplePhotos: [
        {
          fileName: "DJI_0112.JPG",
          createDate: "2025-09-19 05:20:49",
          lat: 38.907203,
          lon: -77.036964,
          altitude: 48.7,
          gimbalPitch: 0.0,
          gimbalYaw: 103.3,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0127.JPG",
          createDate: "2025-09-19 05:21:19",
          lat: 38.907241,
          lon: -77.036865,
          altitude: 48.8,
          gimbalPitch: 0.0,
          gimbalYaw: -129.4,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0142.JPG",
          createDate: "2025-09-19 05:21:49",
          lat: 38.907191,
          lon: -77.036842,
          altitude: 48.7,
          gimbalPitch: 0.0,
          gimbalYaw: -54.3,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0157.JPG",
          createDate: "2025-09-19 05:22:19",
          lat: 38.907159,
          lon: -77.036896,
          altitude: 48.7,
          gimbalPitch: 0.0,
          gimbalYaw: 15.3,
          imageWidth: 5280
        }
      ],
      version: 1
    },
    {
      id: "center-out",
      category: "Center out",
      rawCategory: "center out",
      photoCount: 61,
      orbitType: "full",
      totalRotation: 365.0,
      medianPitch: 0.0,
      medianAltitude: 49.1,
      imageWidth: 5280,
      rule: "pitch 0° within ±3° of 0°, heading away from tower → Center out",
      qaStatus: "PASSED",
      samplePhotos: [
        {
          fileName: "DJI_0233.JPG",
          createDate: "2025-09-19 05:25:51",
          lat: 38.907227,
          lon: -77.036962,
          altitude: 48.9,
          gimbalPitch: 0.0,
          gimbalYaw: -54.0,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0248.JPG",
          createDate: "2025-09-19 05:26:21",
          lat: 38.907155,
          lon: -77.036893,
          altitude: 49.1,
          gimbalPitch: 0.0,
          gimbalYaw: -153.6,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0263.JPG",
          createDate: "2025-09-19 05:26:51",
          lat: 38.907188,
          lon: -77.036834,
          altitude: 49.0,
          gimbalPitch: 0.0,
          gimbalYaw: 108.6,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0278.JPG",
          createDate: "2025-09-19 05:27:21",
          lat: 38.907237,
          lon: -77.036906,
          altitude: 49.1,
          gimbalPitch: 0.0,
          gimbalYaw: 18.3,
          imageWidth: 5280
        }
      ],
      version: 1
    },
    {
      id: "center-in-refly",
      category: "Center in (re-fly)",
      rawCategory: "center in",
      photoCount: 31,
      orbitType: "N/A",
      totalRotation: null,
      medianPitch: -1.0,
      medianAltitude: 6.2,
      imageWidth: 5280,
      rule: "pitch −1° within ±3° of 0°, heading toward tower → Center in",
      qaStatus: "PASSED",
      samplePhotos: [
        {
          fileName: "DJI_0001.JPG",
          createDate: "2025-09-19 05:15:43",
          lat: 38.907246,
          lon: -77.03688,
          altitude: 6.1,
          gimbalPitch: -30.0,
          gimbalYaw: -172.7,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0008.JPG",
          createDate: "2025-09-19 05:15:57",
          lat: 38.907215,
          lon: -77.036805,
          altitude: 6.1,
          gimbalPitch: -30.0,
          gimbalYaw: -102.9,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0015.JPG",
          createDate: "2025-09-19 05:16:11",
          lat: 38.907156,
          lon: -77.036815,
          altitude: 6.2,
          gimbalPitch: -30.0,
          gimbalYaw: -33.9,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0022.JPG",
          createDate: "2025-09-19 05:16:25",
          lat: 38.907144,
          lon: -77.036894,
          altitude: 6.2,
          gimbalPitch: -30.0,
          gimbalYaw: 42.3,
          imageWidth: 5280
        }
      ],
      version: 2,
      note: "Re-flown after v1 flagged ambiguous gimbal angle."
    },
    {
      id: "cable-run",
      category: "Cable run",
      rawCategory: "cable run",
      photoCount: 18,
      orbitType: "N/A",
      totalRotation: null,
      medianPitch: -24.9,
      medianAltitude: 37.75,
      imageWidth: 5280,
      rule: "pitch -25° within ±3° of −22°, altitude 38m > 20m → Cable run",
      qaStatus: "PASSED",
      samplePhotos: [
        {
          fileName: "DJI_0032.JPG",
          createDate: "2025-09-19 05:17:17",
          lat: 38.907197,
          lon: -77.036971,
          altitude: 21.2,
          gimbalPitch: -24.9,
          gimbalYaw: 101.3,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0036.JPG",
          createDate: "2025-09-19 05:17:25",
          lat: 38.907196,
          lon: -77.036971,
          altitude: 29.1,
          gimbalPitch: -24.9,
          gimbalYaw: 101.0,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0040.JPG",
          createDate: "2025-09-19 05:17:33",
          lat: 38.907196,
          lon: -77.036971,
          altitude: 37.0,
          gimbalPitch: -24.9,
          gimbalYaw: 101.0,
          imageWidth: 5280
        },
        {
          fileName: "DJI_0044.JPG",
          createDate: "2025-09-19 05:17:41",
          lat: 38.907196,
          lon: -77.03697,
          altitude: 44.2,
          gimbalPitch: -24.9,
          gimbalYaw: 101.0,
          imageWidth: 5280
        }
      ],
      version: 1
    }
  ],
  replacedSegmentId: "unknown-flight-category-check-gimbal-angle"
};

export const tolerances = {
  gimbalDeg: 3.0,
  fullOrbitDeg: 350.0,
  partialOrbitMinDeg: 70.0
} as const;
