import Image from "next/image";
import {
  ProofGrid,
  StackList,
  Writeup,
  WriteupHeader,
  WriteupSection,
  WriteupTwoCol,
} from "@/components/Writeup";

export const metadata = {
  title: "SpotCheck Hybrid Visual Verification Pipeline | John James",
  description:
    "Case study of a public-safe SpotCheck visual verification demonstrator using OCR anchors, VLM fallback, structured JSON output, and human review flags.",
};

export default function SpotCheckHybridVisualVerificationCaseStudy() {
  return (
    <>
      <main className="flex-1">
        <section className="px-5 md:px-10 py-10 md:py-16">
          <div className="max-w-6xl mx-auto flex flex-col gap-8">
            <header className="max-w-3xl flex flex-col gap-4">
              <span className="text-xs font-mono text-[var(--muted)] uppercase tracking-wider">
                case study
              </span>
              <h1 className="font-display text-4xl md:text-6xl leading-[1.05] tracking-tight">
                SpotCheck hybrid visual verification pipeline
              </h1>
              <p className="text-base md:text-lg text-[var(--muted)] leading-relaxed max-w-2xl">
                A public-safe version of the private SpotCheck visual verifier, rebuilt on open
                models so the architecture can be inspected without exposing client inspection
                data.
              </p>
            </header>

            <figure className="flex flex-col gap-3">
              <div className="relative aspect-[16/10] overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--panel-2)]">
                <Image
                  src="/spotcheck-hybrid-visual-verification-composite.png"
                  alt="Annotated telecom breaker panel with color-coded extraction boxes and structured JSON output."
                  fill
                  priority
                  sizes="(min-width: 1024px) 1024px, 100vw"
                  className="object-cover"
                />
              </div>
              <figcaption className="text-xs text-[var(--muted)] leading-relaxed max-w-3xl">
                The composite is generated by the demonstrator from a public-safe telecom rectifier
                panel photo: detected breaker regions on the left, structured extraction records on
                the right.
              </figcaption>
            </figure>
          </div>
        </section>
      </main>

      <Writeup>
        <WriteupHeader
          eyebrow="case study"
          title="Public-safe visual verification architecture"
          lede="The production SpotCheck verifier runs against private telecom and civil inspection data. This case study shows the same system shape with open-weight tools and public-safe equipment photos: cheap anchors first, VLM fallback for extraction, and explicit review flags when the evidence is incomplete."
        />

        <WriteupSection title="Why this exists">
          <p>
            Client inspection photos are not portfolio material. The useful thing to show is the
            architecture: how a field-photo verifier finds the right evidence, extracts structured
            records, and refuses to guess when the image does not support the answer.
          </p>
          <p>
            This demonstrator rebuilds that architecture around public-safe panel photos. It uses
            EasyOCR for the text-anchor pass and Florence-2-large for local VLM extraction, then
            writes the same kind of structured record the production verifier persists for review.
          </p>
        </WriteupSection>

        <WriteupSection title="Approach">
          <ol className="flex flex-col gap-2 list-decimal list-outside pl-5 marker:text-[var(--muted)] marker:font-mono">
            <li>
              <span className="text-[var(--accent-2)]">Anchor pass:</span> EasyOCR finds text
              regions, filters circuit-number candidates by column geometry, and drops isolated
              false positives.
            </li>
            <li>
              <span className="text-[var(--accent-2)]">Extraction pass:</span> each detected
              breaker region is cropped with layout-aware direction, upscaled, and sent to
              Florence-2-large for OCR-style extraction.
            </li>
            <li>
              <span className="text-[var(--accent-2)]">Status classification:</span> every breaker
              becomes <code className="text-xs font-mono text-[var(--accent-2)]">complete</code>,{" "}
              <code className="text-xs font-mono text-[var(--accent-2)]">partial</code>, or{" "}
              <code className="text-xs font-mono text-[var(--accent-2)]">needs_review</code> based
              on which fields were actually extracted.
            </li>
            <li>
              <span className="text-[var(--accent-2)]">Review output:</span> uncertain records
              carry structured flag reasons and bounding boxes so a human reviewer can act on the
              failure mode instead of reverse-engineering it from a screenshot.
            </li>
          </ol>
        </WriteupSection>

        <WriteupSection title="Walkthrough">
          <p>
            The hero image shows a telecom rectifier panel processed end to end. The system detected
            all 18 visible circuit positions, filtered a stray &ldquo;RECTIFIER 6&rdquo; label as a
            false positive, extracted visible 30A labels from the lower breakers, and marked masked
            labels as needs-review instead of inventing amperage values.
          </p>
          <ProofGrid
            items={[
              { label: "visible positions", value: "18 / 18" },
              { label: "false positive", value: "filtered" },
              { label: "partial records", value: "10" },
              { label: "needs review", value: "8" },
              { label: "record shape", value: "JSON + boxes" },
              { label: "runtime", value: "~30s" },
            ]}
          />
        </WriteupSection>

        <WriteupTwoCol
          left={{
            title: "What works",
            items: [
              "Position detection on visible circuits after column and continuity filtering.",
              "Amperage extraction where the printed labels are visible and large enough.",
              "Measured bounding boxes from OCR and VLM output, not hand-drawn annotations.",
              "Structured records with position, state, amperage, status, flag reason, and raw model text.",
            ],
          }}
          right={{
            title: "What is intentionally bounded",
            items: [
              "State extraction on this panel is not solved by OCR because the breakers use small indicator windows.",
              "Masked amperage labels are flagged for review rather than guessed.",
              "The demonstrator does not claim production accuracy metrics.",
              "Production SpotCheck uses richer hosted models on private inspection data.",
            ],
          }}
        />

        <WriteupSection title="Why this matters">
          <p>
            The interesting part is not a single VLM call. The system is a multi-stage verifier:
            anchor detection, layout-aware cropping, structured parsing, ambiguity handling,
            confidence-aware status classification, and review queueing.
          </p>
          <p>
            That design transfers to real inspection work because field evidence is uneven. Good
            automation has to surface uncertainty cleanly, not convert every missing field into a
            confident-looking answer.
          </p>
        </WriteupSection>

        <WriteupSection title="Proof points">
          <ul className="flex flex-col gap-2 list-disc list-outside pl-5 marker:text-[var(--muted)]">
            <li>All shown assets are produced by the pipeline running on a real panel photo.</li>
            <li>The same code handles both central-directory and split-directory panel layouts.</li>
            <li>The isolated &ldquo;RECTIFIER 6&rdquo; label is rejected by the anchor continuity filter.</li>
            <li>Partial and needs-review outcomes carry structured reasons instead of silent guesses.</li>
          </ul>
        </WriteupSection>

        <WriteupSection title="Stack">
          <StackList
            items={[
              "Python 3.12",
              "Florence-2-large",
              "EasyOCR",
              "Pillow",
              "pillow-heif",
              "NVIDIA GTX 1070",
              "Structured JSON output",
            ]}
          />
        </WriteupSection>

        <WriteupSection title="Boundaries">
          <p className="text-sm text-[var(--muted)]">
            This is a public demonstrator of the production SpotCheck verification architecture,
            not a substitute for the private production system. The accurate claim is that John
            designed the verification architecture, defined the structured record shape and
            review-flag semantics, built this public-safe demonstrator, and verified it on real
            equipment photos.
          </p>
        </WriteupSection>
      </Writeup>
    </>
  );
}
